// <auto-generated />
using System;
using McfApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace McfApi.Migrations
{
    [DbContext(typeof(EfCoreContext))]
    [Migration("20241115092647_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("McfApi.Models.BPKBModel", b =>
                {
                    b.Property<int>("agreement_number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("agreement_number"));

                    b.Property<DateTime?>("bpkb_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("bpkb_date_in")
                        .HasColumnType("datetime2");

                    b.Property<string>("bpkb_no")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("branch_id")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("created_by")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("faktur_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("faktur_no")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("last_updated_by")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("last_updated_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("location_id")
                        .HasColumnType("int");

                    b.Property<string>("police_no")
                        .HasColumnType("varchar(20)");

                    b.HasKey("agreement_number");

                    b.HasIndex("location_id");

                    b.ToTable("tr_bpkb");
                });

            modelBuilder.Entity("McfApi.Models.StorageLocationModel", b =>
                {
                    b.Property<int>("location_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("location_id"));

                    b.Property<string>("location_name")
                        .HasColumnType("varchar(100)");

                    b.HasKey("location_id");

                    b.ToTable("ms_storage_location");
                });

            modelBuilder.Entity("McfApi.Models.UserModel", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("user_name")
                        .HasColumnType("varchar(20)");

                    b.HasKey("user_id");

                    b.ToTable("ms_user");
                });

            modelBuilder.Entity("McfApi.Models.BPKBModel", b =>
                {
                    b.HasOne("McfApi.Models.StorageLocationModel", "storage_location")
                        .WithMany()
                        .HasForeignKey("location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("storage_location");
                });
#pragma warning restore 612, 618
        }
    }
}
